### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

-> NumPy (Numerical Python) is a library for working with arrays and mathematical operations in Python. It is a fundamental package for scientific computing and data analysis, and is widely used in various fields such as physics, engineering, signal processing, and data science.

* Purpose of NumPy:

The primary purpose of NumPy is to provide an efficient and flexible way to work with large datasets, particularly numerical arrays and matrices. It allows users to perform various mathematical operations, such as linear algebra, Fourier transforms, and random number generation, on these datasets.

* Advantages of NumPy:

1. Efficient Memory Management: NumPy arrays are stored in a contiguous block of memory, which leads to faster access and manipulation of data.

2. Vectorized Operations: NumPy provides an extensive set of vectorized operations, which allow users to perform operations on entire arrays at once, rather than iterating over individual elements. This leads to significant performance improvements.

3. Broadcasting: NumPy's broadcasting rules enable users to perform operations on arrays with different shapes and sizes, making it easy to perform complex operations.

4. Multi-Dimensional Arrays: NumPy supports multi-dimensional arrays, which are essential for many scientific computing and data analysis tasks.

5. Integration with Other Libraries: NumPy is seamlessly integrated with other popular Python libraries, such as SciPy, Pandas, and Matplotlib, making it a central component of the Python data science ecosystem.

* How NumPy Enhances Python's Capabilities:

1. Faster Execution: NumPy's optimized C code and vectorized operations make numerical computations much faster than using pure Python.

2. Concise Code: NumPy's high-level syntax and vectorized operations enable users to write concise and expressive code, making it easier to implement complex algorithms.

3. Memory Efficiency: NumPy's efficient memory management reduces memory usage, making it possible to work with large datasets that would be impractical or impossible to handle with pure Python.

4. Advanced Mathematical Operations: NumPy provides an extensive set of mathematical functions, including linear algebra, Fourier transforms, and random number generation, which are essential for many scientific computing and data analysis tasks.

* Real-World Applications:

1. Scientific Computing: NumPy is widely used in scientific computing for tasks such as numerical simulations, data analysis, and visualization.

2. Data Analysis: NumPy is used in data analysis for tasks such as data cleaning, filtering, and transformation.

3. Machine Learning: NumPy is used in machine learning for tasks such as data preprocessing, feature engineering, and model implementation.

4. Signal Processing: NumPy is used in signal processing for tasks such as filtering, convolution, and Fourier transforms.

### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

-> np.mean() and np.average() are two commonly used functions in NumPy for calculating the mean of an array. While they seem similar, there are subtle differences between them.

* np.mean()

-> np.mean() is a function that calculates the arithmetic mean of an array. It takes an array as input and returns the mean value. The arithmetic mean is calculated by summing all the elements in the array and dividing by the total number of elements.

* np.average()

-> np.average() is a function that calculates the weighted average of an array. It takes an array and an optional weights array as input. If weights are not provided, it defaults to uniform weights, and the function behaves similarly to np.mean(). However, if weights are provided, np.average() calculates the weighted average by multiplying each element in the array by its corresponding weight, summing the products, and dividing by the sum of the weights.

* Key differences:

-> Weights: np.average() allows for weighted averages, while np.mean() does not.

-> Default behavior: When no weights are provided, np.average() defaults to uniform weights, whereas np.mean() always calculates the arithmetic mean.
When to use each:

* Use np.mean() when:

1. You want to calculate the arithmetic mean of an array.

2. You don't have weights or don't want to consider weights in the calculation.

3. You want a simple, unweighted mean.

* Use np.average() when:

1. You want to calculate a weighted average of an array.

2. You have weights or importance values associated with each element in the array.

3. You want to give more importance to certain elements in the calculation.
Example:

In [10]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the mean using np.mean()
mean_val = np.mean(arr)
print(mean_val)  # Output: 3.0

# Calculate the weighted average using np.average()
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
avg_val = np.average(arr, weights=weights)
print(avg_val)  # Output: 3.2


3.0
3.2


-> In this example, np.mean() calculates the arithmetic mean of the array, while np.average() calculates the weighted average using the provided weights.

* In summary, np.mean() is used for calculating the arithmetic mean, while np.average() is used for calculating the weighted average. Choose the function based on whether you need to consider weights in your calculation.

### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for ID and 20 arrays.

--> * Reversing a NumPy array is a common operation in data manipulation and analysis. NumPy provides several methods to reverse an array along different axes. Here are the methods and examples for 1D and 2D arrays:

* Method 1: Using the [::-1] slicing syntax

This method uses Python's slice notation to reverse the array. The [::-1] syntax tells NumPy to start from the end of the array and move backwards to the beginning, stepping backwards by 1 element each time.

--> 1D Array Example:


In [11]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


--> 2D Array Example:

In [12]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
reversed_arr_2d = arr_2d[::-1]
print(reversed_arr_2d)  # Output: [[5 6]
                         #          [3 4]
                         #          [1 2]]

[[5 6]
 [3 4]
 [1 2]]



* Method 2: Using the np.flip() function

The np.flip() function is a more explicit way to reverse an array. It takes an array as input and returns a new array with the elements reversed along the specified axis.

1D Array Example:

In [13]:
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


--> 2D Array Example:

In [14]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
reversed_arr_2d = np.flip(arr_2d, axis=0)  # Reverse along axis 0 (rows)
print(reversed_arr_2d)  # Output: [[5 6]
                         #          [3 4]
                         #          [1 2]]


[[5 6]
 [3 4]
 [1 2]]


* Method 3: Using the np.fliplr() or np.flipud() functions

These functions are specific to reversing arrays along the horizontal (left-right) or vertical (up-down) axes, respectively.

--> 2D Array Example:

In [15]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
reversed_arr_2d_lr = np.fliplr(arr_2d)  # Reverse along horizontal axis
print(reversed_arr_2d_lr)  # Output: [[2 1]
                           #          [4 3]
                           #          [6 5]]

reversed_arr_2d_ud = np.flipud(arr_2d)  # Reverse along vertical axis
print(reversed_arr_2d_ud)  # Output: [[5 6]
                           #          [3 4]
                           #          [1 2]]

[[2 1]
 [4 3]
 [6 5]]
[[5 6]
 [3 4]
 [1 2]]


### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

--> Determining the data type of elements in a NumPy array is crucial for efficient memory management and performance. Here are ways to determine the data type of elements in a NumPy array:

--> Method 1: Using the dtype attribute

The dtype attribute of a NumPy array returns the data type of its elements.e

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64

int32


--> Method 2: Using the numpy.dtype function

The numpy.dtype function returns the data type of an array.

In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print((arr))  # Output: int64

[1 2 3 4 5]


* Importance of data types in memory management and performance:

--> Data types play a vital role in memory management and performance in NumPy arrays. Here's why:

1. Memory allocation: NumPy arrays store elements in contiguous blocks of memory. The data type of the elements determines the amount of memory allocated for each element. For example, an int64 array allocates 8 bytes per element, while a float64 array allocates 8 bytes per element as well. Choosing the correct data type can help reduce memory usage and improve performance.

2. Memory access: When accessing elements in a NumPy array, the data type determines how the memory is accessed. For example, accessing an int64 element requires a 64-bit memory access, while accessing a float64 element requires a 64-bit memory access as well. Using the correct data type can improve memory access performance.

3. Operations and casting: When performing operations on NumPy arrays, the data type of the elements determines the operation's behavior. For example, adding two int64 arrays performs integer addition, while adding two float64 arrays performs floating-point addition. If the data types don't match, NumPy may perform casting, which can lead to performance degradation and potential loss of precision.

4. Cache efficiency: The data type of elements in a NumPy array can affect cache efficiency. For example, an array with a smaller data type (e.g., int32) may fit more elements 
in the cache, leading to better performance, while an array with a larger data type (e.g., float128) may require more cache misses, leading to poorer performance.

### 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

--> In NumPy, an ndarray (short for "n-dimensional array") is a multi-dimensional array of fixed-size, homogeneous elements. It is the core data structure in NumPy, and it provides a powerful way to store and manipulate large datasets.

* Key Features of ndarrays:

1. Multi-dimensional: ndarrays can have any number of dimensions, from 1D (a simple array) to 2D (a matrix), 3D, and beyond.

2. Fixed-size: The size of an ndarray is fixed at creation time, and it cannot be changed later.

3. Homogeneous elements: All elements in an ndarray must have the same data type, such as integers, floating-point numbers, or complex numbers.

4. Contiguous memory allocation: ndarrays store their elements in contiguous blocks of memory, which allows for efficient memory access and manipulation.

5. Vectorized operations: ndarrays support vectorized operations, which means that operations can be performed on entire arrays at once, rather than iterating over individual elements.

* How do ndarrays differ from standard Python lists?

1. Memory allocation: Python lists store their elements in non-contiguous blocks of memory, which can lead to slower access times and more memory usage. ndarrays, on the other hand, store their elements in contiguous blocks of memory, making them more efficient.

2. Data type: Python lists can store elements of different data types, while ndarrays require all elements to have the same data type.

3. Size mutability: Python lists can grow or shrink dynamically, while ndarrays have a fixed size that cannot be changed after creation.

4. Performance: ndarrays are generally faster and more efficient than Python lists, especially for numerical computations and large datasets.

5. Vectorized operations: ndarrays support vectorized operations, which are not available in Python lists.

--> Here's an example to illustrate the difference:

In [18]:
import numpy as np

# Create a Python list
python_list = [1, 2, 3, 4, 5]

# Create a NumPy ndarray
numpy_array = np.array([1, 2, 3, 4, 5])

# Try to perform a vectorized operation on the Python list
try:
    python_list * 2
except TypeError:
    print("Error: Python lists do not support vectorized operations")

# Perform a vectorized operation on the NumPy ndarray
result = numpy_array * 2
print(result)  # Output: [ 2  4  6  8 10]

[ 2  4  6  8 10]


### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

--> Performance Benefits of NumPy Arrays over Python Lists

* NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations. Here are some key advantages:

1. Memory Efficiency:

--> NumPy arrays store elements in contiguous blocks of memory, which leads to better memory locality and reduced memory allocation overhead. This results in:

1. Faster memory access: NumPy arrays can access elements more quickly than Python lists, which store elements in non-contiguous blocks of memory.

2. Less memory usage: NumPy arrays typically use less memory than Python lists, especially for large datasets.

2. Vectorized Operations:

--> NumPy arrays support vectorized operations, which allow you to perform operations on entire arrays at once, rather than iterating over individual elements. This leads to:

1. Faster execution: Vectorized operations are much faster than iterating over individual elements in Python lists.

2. Less overhead: Vectorized operations reduce the overhead of function calls and looping, making them more efficient.

3. Cache Efficiency:

--> NumPy arrays are designed to take advantage of CPU cache hierarchies, which leads to:

1. Faster access: NumPy arrays can fit more elements in the cache, reducing the number of cache misses and improving performance.

2. Better parallelization: NumPy arrays can be parallelized more easily, taking advantage of multi-core processors and GPUs.

4. Optimized Algorithms:

--> NumPy arrays use optimized algorithms for common numerical operations, such as matrix multiplication, convolution, and Fourier transforms. These optimized algorithms are:

1. Faster: Optimized algorithms are often faster than equivalent Python implementations.

2. More accurate: Optimized algorithms can provide more accurate results, especially for complex numerical operations.

5. Integration with Other Libraries:

--> NumPy arrays are widely supported by other scientific computing libraries, such as SciPy, Pandas, and Matplotlib. This leads to:

1. Seamless integration: NumPy arrays can be easily used with other libraries, making it easier to perform complex numerical operations.

2. Broader functionality: NumPy arrays can be used for a wide range of numerical operations, from linear algebra to signal processing and machine learning.

* Benchmarks:

--> To illustrate the performance benefits of NumPy arrays, let's consider some benchmarks:

1. Matrix multiplication: NumPy arrays are approximately 100x faster than Python lists for matrix multiplication.

2. Element-wise operations: NumPy arrays are approximately 10x faster than Python lists for element-wise operations, such as addition and multiplication.

3. Linear algebra operations: NumPy arrays are approximately 50x faster than Python lists for linear algebra operations, such as eigenvalue decomposition and singular value decomposition.

* In conclusion, NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations. By leveraging contiguous memory allocation, vectorized operations, cache efficiency, optimized algorithms, and seamless integration with other libraries, NumPy arrays provide a powerful tool for scientific computing and data analysis.



### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

* Comparing vstack() and hstack() Functions in NumPy

--> In NumPy, vstack() and hstack() are two essential functions for stacking arrays vertically and horizontally, respectively. While they share some similarities, they have distinct differences in their functionality and output.

1. vstack() Function:

--> The vstack() function stacks arrays vertically, which means it concatenates arrays along the first axis (axis=0). It takes a sequence of arrays as input and returns a new array with the stacked elements.

Example:

In [19]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

result = np.vstack((a, b, c))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. hstack() Function:

--> The hstack() function stacks arrays horizontally, which means it concatenates arrays along the second axis (axis=1). It takes a sequence of arrays as input and returns a new array with the stacked elements.

Example:

In [20]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

result = np.hstack((a, b, c))
print(result)


[1 2 3 4 5 6 7 8 9]


* Key Difference

1. Axis: vstack() stacks along the first axis (axis=0), while hstack() stacks along the second axis (axis=1).

2. Shape: The resulting array from vstack() has a shape of (n, m), where n is the number of arrays stacked and m is the length of each array. The resulting array from hstack() has a shape of (1, m*n), where m is the length of each array and n is the number of arrays stacked.

3. Output: vstack() returns a 2D array, while hstack() returns a 1D array.

--> When to Use Each:

* Use vstack() when you need to concatenate arrays along the first axis, such as stacking rows of a matrix.
* Use hstack() when you need to concatenate arrays along the second axis, such as stacking columns of a matri

### 8. Explain the differences between fiipir() and flipud() methods in NumPy, Including their effects on various array dimensions.

-> Differences between fliplr() and flipud() Methods in NumPy

--> In NumPy, fliplr() and flipud() are two methods used to flip arrays along specific axes. While they share some similarities, they have distinct differences in their functionality and effects on various array dimensions.

* fliplr() Method:

--> The fliplr() method flips an array horizontally, which means it reverses the elements along the last axis (axis=-1). It is equivalent to mirroring the array about the vertical axis.

Example:

In [21]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_arr = np.fliplr(arr)
print(flipped_arr)

[[3 2 1]
 [6 5 4]]


* flipud() Method:

The flipud() method flips an array vertically, which means it reverses the elements along the first axis (axis=0). It is equivalent to mirroring the array about the horizontal axis.

Example:

In [22]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
flipped_arr = np.flipud(arr)
print(flipped_arr)

[[4 5 6]
 [1 2 3]]


--> Key Differences:

1. Axis: fliplr() flips along the last axis (axis=-1), while flipud() flips along the first axis (axis=0).

2. Direction: fliplr() flips horizontally (left to right), while flipud() flips vertically (top to bottom).

3. Effect on Dimensions: fliplr() reverses the elements along the columns (last axis), while flipud() reverses the elements along the rows (first axis).

--> Effects on Various Array Dimensions:

1. 1D Arrays: Both fliplr() and flipud() have the same effect on 1D arrays, reversing the elements in the array.

2. 2D Arrays: fliplr() flips the columns, while flipud() flips the rows.

3. 3D Arrays: fliplr() flips the last axis (axis=-1), while flipud() flips the first axis (axis=0). The effects on 3D arrays depend on the specific axis being flipped.

--> When to Use Each:

1. Use fliplr() when you need to flip an array horizontally, such as mirroring an image about the vertical axis.

2. Use flipud() when you need to flip an array vertically, such as mirroring an image about the horizontal axis.

### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Array Splitting with array_split() in NumPy

The array_split() method in NumPy is used to split an array into multiple sub-arrays along a specified axis. It is a convenient function for dividing large arrays into smaller, more manageable pieces.

--> Basic Functionality:

-> The array_split() method takes three arguments:

1. ary: The input array to be split.
2. indices_or_sections: The number of sections to split the array into or a list of indices where the array should be split.
3. axis: The axis along which to split the array (default is 0).

Example:


In [23]:
import numpy as np

arr = np.arange(10)
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Handling Uneven Splits:

When the length of the array is not evenly divisible by the number of sections, array_split() will create sub-arrays of varying lengths. The remaining elements will be distributed among the sub-arrays.

Example: 

In [24]:
import numpy as np

arr = np.arange(11)
split_arr = np.array_split(arr, 3)
print(split_arr)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]


In this example, the array has 11 elements, which cannot be evenly divided into 3 sections. The first two sub-arrays have 4 elements each, and the last sub-array has 3 elements.

* Key Points:

-> array_split() is a flexible function that can handle both even and uneven splits.
-> When the split is uneven, the remaining elements are distributed among the sub-arrays.
-> The axis parameter allows you to split the array along a specific axis, making it useful for multidimensional arrays.

### 10.  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

* Vectorization and Broadcasting in NumPy: Efficient Array Operations

-> NumPy, a fundamental library for numerical computing in Python, provides two essential concepts for efficient array operations: vectorization and broadcasting. These concepts enable NumPy to perform operations on entire arrays at once, making it a powerful tool for data manipulation and analysis.

1. Vectorization:

--> Vectorization is the process of applying a single operation to an entire array, rather than iterating over individual elements. This approach eliminates the need for explicit loops, making NumPy operations faster and more efficient. Vectorization is achieved through the use of universal functions (ufuncs), which are functions that operate on entire arrays.

Example:

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
squared_arr = arr ** 2
print(squared_arr)

[ 1  4  9 16 25]


In this example, the exponentiation operation (** 2) is applied to the entire array arr, resulting in a new array squared_arr with the squared values.

2. Broadcasting:

--> Broadcasting is a set of rules that allow NumPy to perform operations on arrays with different shapes and sizes. It enables the alignment of arrays for element-wise operations, even when the arrays do not have the same shape. Broadcasting is essential for performing operations on arrays with different dimensions.

Example:

In [26]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 4, 4])
result = arr1 + arr2
print(result)

[5 6 7]


In this example, the addition operation is performed element-wise between arr1 and arr2, even though they have different shapes. Broadcasting aligns the arrays to perform the operation.

-> How Vectorization and Broadcasting Contribute to Efficient Array Operations:

1. Speed: Vectorization and broadcasting enable NumPy to perform operations on entire arrays at once, reducing the need for explicit loops and making operations faster.

2. Memory Efficiency: By operating on entire arrays, NumPy minimizes memory allocation and copying, reducing memory usage and improving performance.

3. Flexibility: Broadcasting allows NumPy to perform operations on arrays with different shapes and sizes, making it a versatile tool for data manipulation and analysis.

4. Expressiveness: Vectorization and broadcasting enable concise and expressive code, making it easier to write and maintain complex numerical computations.

# Practical Question


In [27]:
import numpy as np


### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [28]:
a = np.random.randint(1,100,(3,3))
a

array([[39, 19, 79],
       [30,  5, 81],
       [92, 60, 84]])

In [29]:
a.T

array([[39, 30, 92],
       [19,  5, 60],
       [79, 81, 84]])

### 2. Generate a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [30]:
b = np.arange(0,10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
b.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [33]:
c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
C = np.zeros((6,6))
C[1:5,1:5] = c
C



array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  0.],
       [ 0.,  5.,  6.,  7.,  8.,  0.],
       [ 0.,  9., 10., 11., 12.,  0.],
       [ 0., 13., 14., 15., 16.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [35]:
d = np.arange(10,60,5)
d

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [36]:
d.reshape(2,5)

array([[10, 15, 20, 25, 30],
       [35, 40, 45, 50, 55]])

In [37]:
d.reshape(5,2)

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55]])

### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [38]:
e = np.array(["python","numpy","pandas"])
e

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [39]:
np.char.upper(e)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [40]:
np.char.lower(e)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [41]:
np.char.capitalize(e)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [47]:
f = np.array(["python","numpy","pandas"])
print(f)
F = np.char.join(" ",f)
F

['python' 'numpy' 'pandas']


array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [58]:
g = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("g:",g)
h = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("h:",h)

g: [[1 2 3]
 [4 5 6]
 [7 8 9]]
h: [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [59]:
g + h

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [60]:
g - h

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [61]:
g * h

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [62]:
g@h

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [63]:
g/h

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [75]:
i = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
i

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [80]:
np.diag(i)

array([ 1,  7, 13, 19, 25])

### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [112]:
j = np.random.randint(0,1000,(1,100))
j

array([[336, 140, 604, 422,  40, 810, 105,  24, 933, 865, 885, 941, 536,
         55, 887,  47,  33, 709, 612, 609, 976, 414,  63, 732, 933, 707,
        937,  43, 563, 625, 464, 386, 919, 787,  70, 258, 298, 100, 359,
        447, 769, 640, 515, 298, 388, 364, 589, 275, 201, 580, 863, 439,
         99, 365, 989, 812, 239, 323, 546, 981, 912, 420, 630, 304, 734,
        443, 501, 793, 242, 864, 578, 265, 760,  83, 660, 294, 198, 463,
        784, 721,  24, 224, 147, 418, 707, 257, 578, 565, 163, 517, 390,
        822,  81, 698, 217, 818, 925, 677, 839, 560]])

In [113]:
is_prime = np.vectorize(lambda n: n > 1 and all(n % i != 0 for i in range(2, int(np.sqrt(n)) + 1)))
prime_numbers = j[is_prime(j)]
prime_numbers

array([941, 887,  47, 709, 937,  43, 563, 919, 787, 359, 769, 863, 439,
       239, 443,  83, 463, 257, 163, 677, 839])

### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [107]:
k = np.random.randint(10,50,size = 30)
k

array([27, 36, 15, 32, 16, 10, 39, 21, 39, 11, 47, 23, 45, 19, 32, 33, 27,
       32, 36, 16, 40, 42, 40, 33, 13, 21, 44, 16, 40, 14])

In [108]:
l = np.average(k)
print("The Average Temperature: ", l)

The Average Temperature:  28.633333333333333
